import Footer from './Footer'
import Navbar from './Navbar'
import Head from 'next/head'
const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>penstage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Navbar />
      <main className="min-h-screen max-w-[1444px] mx-auto mt-[100px]">
        {children}
      </main>

      <Footer />
    </div>
  )
}
export default Layout
